# Generated by Django 3.2.18 on 2023-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
